---
title: "Analyses of stratified promoters in MPAC-satmut_promoters"
author: "Stephen Rong"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preamble}
# load libraries
library(tidyverse)
library(data.table)
library(viridis)
library(corrplot)

save_path <- "../../results/satmut_promoters_analysis/satmut_promoters_strat_promoters/"
dir.create(save_path, showWarnings = FALSE, recursive = TRUE)

# load tables
satmut_promoters_gene_metadata <- as_tibble(fread("../../data/satmut_promoters_preprocess/satmut_promoters_gene_metadata/satmut_promoters_gene_metadata.txt.gz")) %>%
  mutate(s_het_bin = ntile(s_het, 10)) %>%
  mutate(loeuf_bin = ntile(loeuf, 10)) %>%
  mutate(moeuf_bin = ntile(moeuf, 10)) %>%
  mutate(alphmis_bin = ntile(alphmis, 10))

# constraint measure correlation plot
pdf(paste0(save_path, "satmut_prom_strat_constraint_corr.pdf"), height=3, width=3)
corrplot(cor(satmut_promoters_gene_metadata %>% dplyr::select(s_het, loeuf, moeuf, alphmis),
             use = "pairwise.complete.obs"), 
  order="original", method="square", tl.pos="lt", type="upper", 
  tl.col="black", tl.cex=0.6, tl.srt=90, 
  addCoef.col="black",
  pch = ""
)
dev.off()

satmut_promoters_final_base <- list()
for (chr in paste0("chr", c(1:22))) {
  print(chr)
  satmut_promoters_final_base[[chr]] <- as_tibble(fread(paste0("../../data/satmut_promoters_preprocess/satmut_promoters_final_base/satmut_promoters_final_base_", chr, ".txt.gz"))) %>% 
    filter(in_promoter_250bp) %>% 
    filter(!in_all_exon_splice)
}

satmut_promoters_final_base <- satmut_promoters_final_base %>% 
  bind_rows() %>% 
  left_join(satmut_promoters_gene_metadata)

skew_bins <- c(-Inf, -1.5, -1, -0.5, -0.2, -0.05, 0.05, 0.2, 0.5, 1, 1.5, Inf)
```

```{r helper-function}
# Helper: compute phyloP-by-skew summary stratified by a constraint decile,
# save table and plot
plot_strat_phylop_by_skew <- function(df, bin_col, bin_label, file_tag,
                                       dodge_width = 0.9) {
  summary_df <- df %>% 
    filter(in_promoter_250bp) %>% 
    filter(!in_all_exon_splice) %>% 
    filter(!is.na(.data[[bin_col]])) %>% 
    group_by(
      avgKHS_skew_base_bin = cut(avgKHS_skew_base, breaks = skew_bins), 
      !!sym(bin_col) := as.factor(.data[[bin_col]])
    ) %>% 
    filter(dplyr::n() >= 50) %>% 
    summarise(
      count_n = dplyr::n(), 
      phyloP_mam241_base_mean = mean(phyloP_mam241_base, na.rm = TRUE), 
      phyloP_mam241_base_sd = sd(phyloP_mam241_base, na.rm = TRUE), 
    ) %>% 
    mutate(
      phyloP_mam241_base_se = phyloP_mam241_base_sd / sqrt(count_n),
      phyloP_mam241_base_lci = phyloP_mam241_base_mean - 1.96 * phyloP_mam241_base_se,
      phyloP_mam241_base_uci = phyloP_mam241_base_mean + 1.96 * phyloP_mam241_base_se
    ) %>% 
    ungroup()
  
  write_tsv(summary_df, paste0(save_path, "satmut_prom_strat_phylop_by_skew_", file_tag, ".txt"))
  
  ggplot(summary_df) + 
    geom_hline(yintercept = 0, color = "black") + 
    geom_line(aes(x = avgKHS_skew_base_bin, y = phyloP_mam241_base_mean,
                  color = .data[[bin_col]], group = .data[[bin_col]]),
              position = position_dodge(width = dodge_width), alpha = 0.3) + 
    geom_point(aes(x = avgKHS_skew_base_bin, y = phyloP_mam241_base_mean,
                   color = .data[[bin_col]]),
               position = position_dodge(width = dodge_width)) + 
    geom_errorbar(aes(x = avgKHS_skew_base_bin, 
      ymin = phyloP_mam241_base_mean - 1.96 * phyloP_mam241_base_se, 
      ymax = phyloP_mam241_base_mean + 1.96 * phyloP_mam241_base_se, 
      color = .data[[bin_col]]), 
      width = 0.2, position = position_dodge(width = dodge_width)) + 
    geom_hline(yintercept = 2.27, color = "orange", linetype = "dashed") + 
    theme_classic() + 
    scale_color_viridis_d() + 
    scale_fill_viridis_d() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
          axis.line.x = element_blank()) +   
    labs(x = "Mean allelic skew", y = "Mean phyloP", color = bin_label) + 
    guides(fill = "none") + 
    ylim(c(0, 7))
  ggsave(paste0(save_path, "satmut_prom_strat_phylop_by_skew_", file_tag, ".pdf"))

  ggplot(summary_df) + 
    geom_hline(yintercept = 0, color = "black") + 
    geom_line(aes(x = avgKHS_skew_base_bin, y = phyloP_mam241_base_mean,
                  color = .data[[bin_col]], group = .data[[bin_col]]),
              position = position_dodge(width = dodge_width), alpha = 0.3) + 
    geom_point(aes(x = avgKHS_skew_base_bin, y = phyloP_mam241_base_mean,
                   color = .data[[bin_col]]),
               position = position_dodge(width = dodge_width)) + 
    geom_errorbar(aes(x = avgKHS_skew_base_bin, 
      ymin = phyloP_mam241_base_mean - 1.96 * phyloP_mam241_base_se, 
      ymax = phyloP_mam241_base_mean + 1.96 * phyloP_mam241_base_se, 
      color = .data[[bin_col]]), 
      width = 0.2, position = position_dodge(width = dodge_width)) + 
    geom_hline(yintercept = 2.27, color = "orange", linetype = "dashed") + 
    theme_classic() + 
    scale_color_viridis_d() + 
    scale_fill_viridis_d() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
          axis.line.x = element_blank(),
          aspect.ratio = 1) +   
    labs(x = "Mean allelic skew", y = "Mean phyloP", color = bin_label) + 
    guides(fill = "none") + 
    ylim(c(0, 7))
  ggsave(paste0(save_path, "satmut_prom_strat_phylop_by_skew_", file_tag, "_skinny.pdf"))
}
```

```{r stratify promoters}
# s_het
plot_strat_phylop_by_skew(satmut_promoters_final_base, "s_het_bin", expression(italic(s)[het] ~ "decile"), "s_het")

# loeuf (negative dodge for reversed scale)
plot_strat_phylop_by_skew(satmut_promoters_final_base, "loeuf_bin", "LOEUF decile", "loeuf",
                          dodge_width = -0.9)

# alphmis
plot_strat_phylop_by_skew(satmut_promoters_final_base, "alphmis_bin", "AlphMis decile", "alphmis")

# moeuf (negative dodge for reversed scale)
plot_strat_phylop_by_skew(satmut_promoters_final_base, "moeuf_bin", "MOEUF decile", "moeuf",
                          dodge_width = -0.9)
```

```{r correlation change with s_het}
# stratified correlations, phyloP and skew by s_het
strat_cor <- satmut_promoters_final_base %>% 
  filter(!is.na(s_het_bin)) %>% 
  group_by(s_het_bin) %>%
  summarise(cor_abs_avgKHS_phyloP_pos = cor(avgKHS_abs_skew_base, phyloP_mam241_pos_base, use = "pairwise.complete.obs", method = "spearman")) %>%
  ungroup()

# global correlation, phyloP and skew
global_cor <- satmut_promoters_final_base %>% 
  summarise(cor_abs_avgKHS_phyloP_pos = cor(avgKHS_abs_skew_base, phyloP_mam241_pos_base, use = "pairwise.complete.obs", method = "spearman")) %>%
  ungroup()

# global correlation, phyloP and s_het only
global_shet_cor <- satmut_promoters_final_base %>% 
  summarise(cor_abs_avgKHS_phyloP_pos = cor(s_het, phyloP_mam241_pos_base, use = "pairwise.complete.obs", method = "spearman")) %>%
  ungroup()

# weighted correlation, phyloP and skew x s_het
weighted_cor <- satmut_promoters_final_base %>% 
  summarise(cor_abs_avgKHS_phyloP_pos = cor(avgKHS_abs_skew_base*s_het, phyloP_mam241_pos_base, use = "pairwise.complete.obs", method = "spearman")) %>%
  ungroup()

ggplot(strat_cor) + 
  geom_hline(aes(yintercept = global_cor$cor_abs_avgKHS_phyloP_pos), linetype = "dashed") + 
  geom_point(aes(as.factor(s_het_bin), cor_abs_avgKHS_phyloP_pos, color = as.factor(s_het_bin)), size = 3) + 
  theme_classic() + 
  scale_color_viridis_d() + 
  ylim(c(0, 0.3)) + 
  xlab(expression(italic(s)[het] ~ "decile")) + 
  ylab(expression("Spearman's" ~ rho * "(" * "max(0, phyloP), |allelic skew|" * ")")) + 
  guides(color = "none") + 
  labs(color = "s_het decile") + 
  theme(aspect.ratio = 1/1.6)
ggsave(paste0(save_path, "satmut_prom_strat_cor_by_shet.pdf"), scale = 0.7)

write_tsv(strat_cor, paste0(save_path, "satmut_prom_strat_cor_by_shet.txt"))
write_tsv(global_cor, paste0(save_path, "satmut_prom_strat_cor_global.txt"))
```
