---
title: "Analyses of correlations of promoters in MPAC-satmut_promoters"
author: "Stephen Rong"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preamble}
# load libraries
library(tidyverse)
library(data.table)
library(viridis)
library(patchwork)
library(corrplot)
library(GGally)

save_path <- "../../results/satmut_promoters_analysis/satmut_promoters_overall_corr/"
dir.create(save_path, showWarnings = FALSE, recursive = TRUE)

# load tables
satmut_promoters_pred_final_base_level <- list()
for (chr in paste0("chr", c(1:22))) {
	print(chr)
	satmut_promoters_pred_final_base_level[[chr]] <- as_tibble(fread(paste0("../../data/satmut_promoters_preprocess/satmut_promoters_final_base/satmut_promoters_final_base_", chr, ".txt.gz"))) %>%  
		filter(!in_all_exon_splice)
}

satmut_promoters_pred_final_base_level <- satmut_promoters_pred_final_base_level %>% 
	bind_rows()
```

```{r some counts}
# what proportion of emvars are within 250bp
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_base)
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_base)
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_base)/
  sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_base)

# what proportion of emvars are negative
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_neg_base)
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_neg_base)/
  sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_base)

sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_neg_base)
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_neg_base)/
  sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_base)

# what proportion of emvars are positive
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_pos_base)
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_pos_base)/
  sum(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb)$avgKHS_emVar_base)

sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_pos_base)
sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_pos_base)/
  sum(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp)$avgKHS_emVar_base)

# of the negative emVars, what is their mean allelic-skew
mean(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb, avgKHS_emVar_neg_base > 0)$avgKHS_skew_base, na.rm=T)
mean(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp, avgKHS_emVar_neg_base > 0)$avgKHS_skew_base, na.rm=T)

# of the positive emVars, what is their mean allelic-skew
mean(filter(satmut_promoters_pred_final_base_level, in_promoter_1kb, avgKHS_emVar_pos_base > 0)$avgKHS_skew_base, na.rm=T)
mean(filter(satmut_promoters_pred_final_base_level, in_promoter_250bp, avgKHS_emVar_pos_base > 0)$avgKHS_skew_base, na.rm=T)
```

```{r helper-function}
# Helper: compute correlation matrix, save corrplot PDF and source TSV
save_corrplot <- function(df, columns, rename_map, file_stem, width = 3, height = 3) {
  cor_mat <- cor(
    df %>% dplyr::select(all_of(columns)) %>% dplyr::rename(!!!rename_map),
    use = "na.or.complete",
    method = "spearman"
  )
  # Save source table
  write.csv(cor_mat, paste0(save_path, file_stem, ".csv"))
  # Save corrplot
  pdf(paste0(save_path, file_stem, ".pdf"), width = width, height = height)
  corrplot(cor_mat,
    order = "original", method = "square", tl.pos = "lt", type = "upper",
    tl.col = "black", tl.cex = 0.6, tl.srt = 90,
    addCoef.col = "black",
    pch = ""
  )
  dev.off()
}
```

```{r correlations}
# Skew correlations

# All positions
save_corrplot(
  satmut_promoters_pred_final_base_level,
  columns = c("phyloP_mam241_pos_base", "K562_abs_skew_base", "HepG2_abs_skew_base", "SKNSH_abs_skew_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 |allelic skew|` = "K562_abs_skew_base",
    `HepG2 |allelic skew|` = "HepG2_abs_skew_base",
    `SKNSH |allelic skew|` = "SKNSH_abs_skew_base"
  ),
  file_stem = "satmut_prom_corr_skew"
)

# 250bp
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_250bp),
  columns = c("phyloP_mam241_pos_base", "K562_abs_skew_base", "HepG2_abs_skew_base", "SKNSH_abs_skew_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 |allelic skew|` = "K562_abs_skew_base",
    `HepG2 |allelic skew|` = "HepG2_abs_skew_base",
    `SKNSH |allelic skew|` = "SKNSH_abs_skew_base"
  ),
  file_stem = "satmut_prom_corr_skew_250bp"
)

# 251-500bp
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_500bp, !in_promoter_250bp),
  columns = c("phyloP_mam241_pos_base", "K562_abs_skew_base", "HepG2_abs_skew_base", "SKNSH_abs_skew_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 |allelic skew|` = "K562_abs_skew_base",
    `HepG2 |allelic skew|` = "HepG2_abs_skew_base",
    `SKNSH |allelic skew|` = "SKNSH_abs_skew_base"
  ),
  file_stem = "satmut_prom_corr_skew_500bp"
)

# 501-750bp
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_750bp, !in_promoter_500bp),
  columns = c("phyloP_mam241_pos_base", "K562_abs_skew_base", "HepG2_abs_skew_base", "SKNSH_abs_skew_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 |allelic skew|` = "K562_abs_skew_base",
    `HepG2 |allelic skew|` = "HepG2_abs_skew_base",
    `SKNSH |allelic skew|` = "SKNSH_abs_skew_base"
  ),
  file_stem = "satmut_prom_corr_skew_750bp"
)

# 751bp-1kb
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_1kb, !in_promoter_750bp),
  columns = c("phyloP_mam241_pos_base", "K562_abs_skew_base", "HepG2_abs_skew_base", "SKNSH_abs_skew_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 |allelic skew|` = "K562_abs_skew_base",
    `HepG2 |allelic skew|` = "HepG2_abs_skew_base",
    `SKNSH |allelic skew|` = "SKNSH_abs_skew_base"
  ),
  file_stem = "satmut_prom_corr_skew_1kb"
)

# Activity correlations

# All positions
save_corrplot(
  satmut_promoters_pred_final_base_level,
  columns = c("phyloP_mam241_pos_base", "K562_activity_base", "HepG2_activity_base", "SKNSH_activity_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 activity` = "K562_activity_base",
    `HepG2 activity` = "HepG2_activity_base",
    `SKNSH activity` = "SKNSH_activity_base"
  ),
  file_stem = "satmut_prom_corr_activity"
)

# 250bp
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_250bp),
  columns = c("phyloP_mam241_pos_base", "K562_activity_base", "HepG2_activity_base", "SKNSH_activity_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 activity` = "K562_activity_base",
    `HepG2 activity` = "HepG2_activity_base",
    `SKNSH activity` = "SKNSH_activity_base"
  ),
  file_stem = "satmut_prom_corr_activity_250bp"
)

# 251-500bp
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_500bp, !in_promoter_250bp),
  columns = c("phyloP_mam241_pos_base", "K562_activity_base", "HepG2_activity_base", "SKNSH_activity_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 activity` = "K562_activity_base",
    `HepG2 activity` = "HepG2_activity_base",
    `SKNSH activity` = "SKNSH_activity_base"
  ),
  file_stem = "satmut_prom_corr_activity_500bp"
)

# 501-750bp
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_750bp, !in_promoter_500bp),
  columns = c("phyloP_mam241_pos_base", "K562_activity_base", "HepG2_activity_base", "SKNSH_activity_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 activity` = "K562_activity_base",
    `HepG2 activity` = "HepG2_activity_base",
    `SKNSH activity` = "SKNSH_activity_base"
  ),
  file_stem = "satmut_prom_corr_activity_750bp"
)

# 751bp-1kb
save_corrplot(
  satmut_promoters_pred_final_base_level %>% filter(in_promoter_1kb, !in_promoter_750bp),
  columns = c("phyloP_mam241_pos_base", "K562_activity_base", "HepG2_activity_base", "SKNSH_activity_base"),
  rename_map = c(
    `max(0, phyloP)` = "phyloP_mam241_pos_base",
    `K562 activity` = "K562_activity_base",
    `HepG2 activity` = "HepG2_activity_base",
    `SKNSH activity` = "SKNSH_activity_base"
  ),
  file_stem = "satmut_prom_corr_activity_1kb"
)
```
